require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rnProject' do

  pod 'BaiduMapKit', '6.3.0'
  pod 'BMKLocationKit'
  pod 'AMapNavi'
 
  pod 'UMCCommon', '2.1.1'
  pod 'UMCSecurityPlugins', '1.0.6'
  pod 'UMCCommonLog', '1.0.0'
  pod 'UMCShare/UI', '6.9.6'
  pod 'UMCShare/Social/ReducedWeChat', '6.9.6'
  pod 'UMCShare/Social/WeChat', '6.9.6'
  pod 'UMCShare/Social/ReducedQQ', '6.9.6'
  pod 'UMCShare/Social/QQ', '6.9.6'

  # pod 'UMCommon'
  # pod 'UMDevice'
  # pod 'UMShare/UI'
  # pod 'UMShare/Social/WeChat'
  # pod 'UMShare/Social/QQ'
  pod 'Bugly'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'rnProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
        end
    end
  end
end

target 'rnProject-tvOS' do
  # Pods for rnProject-tvOS

  target 'rnProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
